/**
 * Regenerates src/data/generated/articles.ts from the CMS markdown files in
 * content/articles. Runs automatically before `next build` so CMS edits are
 * reflected in the static site.
 *
 * Run: node scripts/sync-content.mjs
 */
import { mkdirSync, readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import matter from 'gray-matter';

const contentDir = join(process.cwd(), 'content/articles');
const generatedDir = join(process.cwd(), 'src/data/generated');
const outFile = join(generatedDir, 'articles.ts');

mkdirSync(contentDir, { recursive: true });
mkdirSync(generatedDir, { recursive: true });

const files = readdirSync(contentDir).filter((f) => f.endsWith('.md'));

const articles = files.map((file) => {
  const raw = readFileSync(join(contentDir, file), 'utf8');
  const { data, content } = matter(raw);
  const date = String(data.date || '').slice(0, 10);
  return {
    slug: data.slug || file.replace(/\.md$/, ''),
    title: data.title || '',
    description: data.description || '',
    content,
    image: data.image || '',
    category: data.category || 'guide',
    readTime: Number(data.readTime) || 5,
    date,
    tags: Array.isArray(data.tags) ? data.tags.map(String) : [],
    relatedGear: Array.isArray(data.relatedGear) ? data.relatedGear.map(String) : [],
    ...(data.lang ? { lang: String(data.lang) } : {}),
  };
});

articles.sort((a, b) => (a.date < b.date ? 1 : a.date > b.date ? -1 : 0));

const lines = articles.map((a) => `  ${JSON.stringify(a)},`);
const out = [
  '// AUTO-GENERATED by scripts/sync-content.mjs - do not edit by hand.',
  '// Source of truth: content/articles/*.md (managed via the TinaCMS admin).',
  "import type { Article } from '../articles-fallback';",
  '',
  'export const generatedArticles: Article[] = [',
  ...lines,
  '];',
  '',
].join('\n');

writeFileSync(outFile, out);
console.log(`Synced ${articles.length} articles -> ${outFile}`);
